services:
  load-balancer:
    build: 
      context: .
      dockerfile: Docker.nginx
    image: chhat/load-nginx:v1.1
    depends_on:
      - express
    environment:
      - EXPRESS_HOST_1=devops-dev-express-1
      - EXPRESS_HOST_2=devops-dev-express-2

      - EXPRESS_PORT=3000
      - NGINX_SERVER_NAME=localhost
      - NGINX_MAX_BODY=100M
    ports:
      - 3000:3000
    networks:
      - chhat-network

  express:
    build:
      context: .
      dockerfile: Dockerfile
    image: chhat/devops-express:v1.0
    command: npx nodemon --legacy-watch src/server.js  
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    environment:
      - NODE_ENV=dev
    depends_on:
      - database
    scale: 2
    networks:
      - chhat-network

  database:
    image: mongo:8.2.7-noble
    container_name: devops-database-dev
    ports:
      - 27017:27017
    networks:
      - chhat-network
    volumes:
      - devops-db-dev:/data/db

volumes:
  devops-db-dev:
networks:
  chhat-network: